### ISSUE TITLE
protobuf 2 only?

### ISSUE THREAD

**Issue by mrosseel** [royaltm/inspect-protobuf#1]
Is this tool protobuf 2 only?
Testing this with protobuf 3 and getting these kind of errors:

{ Error: 'Error: Unknown wire type: 6' }
{ Error: 'Error: Groups are not supported' }

**Comment by royaltm** [comment]
it supports whatever https://www.npmjs.com/package/protocol-buffers supports, didn't test with protobuf 3 though

**Comment by mrosseel** [comment]
relevant bugs from the project you mentioned (which have been open for a while):

https://github.com/mafintosh/protocol-buffers/issues/58
https://github.com/mafintosh/protocol-buffers/issues/17

At first glance it seems this project: https://www.npmjs.com/package/protobufjs
might be a better backend. Hope it gets fixed somehow, seems like a useful tool!

**Comment by royaltm** [comment]
Thanks for the feedback, I'll look into it.

**Comment by royaltm** [comment]
@mrosseel try 1.1.0 version with argument `-3`

**Comment by mrosseel** [comment]
Hi, Tried it:

    cat Preferences | inspect-protobuf 
    ~/dev/projects/common/src/main/proto/pb.proto PersistableEnvelope
    { Error: 'Error: Groups are not supported' }

    cat Preferences | inspect-protobuf -3 
    ~/dev/projects/common/src/main/proto/pb.proto PersistableEnvelope

    Error: no such protobuf message: "PersistableEnvelope"

**Comment by royaltm** [comment]
you need to specify package name prefixed message name in -3 version
```
cat Preferences | inspect-protobuf -3 \
~/dev/projects/common/src/main/proto/pb.proto blahblahblah.PersistableEnvelope
```
where `blahblahblah` is on the top of your proto file, e.g.:
```
package blahblahblah;
````
